[build]
  command = "pip install -r requirements.txt && python build.py"
  publish = "public"
  environment = { PYTHON_VERSION = "3.11" }

[build.environment]
  PYTHON_VERSION = "3.11"
  PIP_VERSION = "24.0"
  NODE_VERSION = "18"

[[redirects]]
  from = "/blog/cat-breeds"
  to = "/blog/breeds/index.html"
  status = 200

[[redirects]]
  from = "/blog/breeds"
  to = "/blog/breeds/index.html"
  status = 200

[[redirects]]
  from = "/blog/breeds/*"
  to = "/blog/breeds/:splat"
  status = 200

[[redirects]]
  from = "/blog/guides-and-tips"
  to = "/blog/guides-and-tips/index.html"
  status = 200

[[redirects]]
  from = "/blog/guidesandtips"
  to = "/blog/guides-and-tips/index.html"
  status = 200

[[redirects]]
  from = "/blog/behavior/understanding-maine-coon-behavior"
  to = "/blog/behavior/cat-maine-coon-behavior.html"
  status = 200

[[redirects]]
  from = "/blog/behavior/training-tips"
  to = "/blog/behavior/cat-training-tips.html"
  status = 200

[[redirects]]
  from = "/blog/behavior/socialization"
  to = "/blog/behavior/cat-socialization.html"
  status = 200

[[redirects]]
  from = "/blog/*"
  to = "/blog/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https: data: 'unsafe-inline' 'unsafe-eval';"

[[plugins]]
  package = "@netlify/plugin-gatsby" 