[build]
  publish = "."
  command = "echo 'No build command needed for static site'"

[[redirects]]
  from = "/blog/cat-breeds"
  to = "/blog/breeds/index.html"
  status = 200

[[redirects]]
  from = "/blog/breeds"
  to = "/blog/breeds/index.html"
  status = 200

[[redirects]]
  from = "/blog/breeds/*"
  to = "/blog/breeds/:splat"
  status = 200

[[redirects]]
  from = "/blog/guides-and-tips"
  to = "/blog/guides-and-tips/index.html"
  status = 200

[[redirects]]
  from = "/blog/guidesandtips"
  to = "/blog/guides-and-tips/index.html"
  status = 200

[[redirects]]
  from = "/blog/behavior/understanding-maine-coon-behavior"
  to = "/blog/behavior/cat-maine-coon-behavior.html"
  status = 200

[[redirects]]
  from = "/blog/behavior/training-tips"
  to = "/blog/behavior/cat-training-tips.html"
  status = 200

[[redirects]]
  from = "/blog/behavior/socialization"
  to = "/blog/behavior/cat-socialization.html"
  status = 200

[[redirects]]
  from = "/blog/*"
  to = "/blog/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https: data: 'unsafe-inline' 'unsafe-eval';" 